### ISSUE TITLE
Collection error when trying to delete object

### ISSUE THREAD

**Issue by gjost** [denshoproject/ddr-local#313]
sara.beckman: Tried to delete object 2 in ddr-densho-461 in Editor and got this failure message
```
Traceback (most recent call last):
  File "/opt/ddr-local/venv/ddrlocal/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/ddr-local/venv/ddrlocal/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/ddr-local/ddrlocal/webui/tasks/entity.py", line 163, in entity_delete
    status,message = entity.delete(
  File "/opt/ddr-local/venv/ddrlocal/lib/python3.9/site-packages/ddr_cmdln-5.4.5-py3.9.egg/DDR/models/entity.py", line 284, in delete
    parent.remove_child(self.id)
AttributeError: 'Collection' object has no attribute 'remove_child'
```

**Comment by gjost** [comment]
Fixed in commits merged into `ddr-cmdln` `master` branch in `5a77c2f`, and in `ddr-local` `master` branch in `c96e075`.
