### ISSUE TITLE
`path_abs` missing from new file uploads from the web UI

### ISSUE THREAD

**Issue by gjost** [denshoproject/ddr-local#321]
sara.beckman: Imported VM 5.6_HQMA - I added a new entity to `ddr-testing-40410` (object 61) tried to add a master file to `ddr-testing-40410` from my `ddrshared` folder and received a failure message:
```
Traceback (most recent call last):
  File "/opt/ddr-local/venv/ddrlocal/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/ddr-local/venv/ddrlocal/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/ddr-local/ddrlocal/webui/tasks/files.py", line 185, in file_add_local
    file_,repo,log = entity.add_local_file(
  File "/opt/ddr-local/venv/ddrlocal/lib/python3.9/site-packages/ddr_cmdln-5.6.0-py3.9.egg/DDR/models/entity.py", line 650, in add_local_file
    return ingest.add_file(data, self, git_name, git_mail, agent)
  File "/opt/ddr-local/venv/ddrlocal/lib/python3.9/site-packages/ddr_cmdln-5.6.0-py3.9.egg/DDR/ingest.py", line 113, in add_file
    src_path = rowd.pop('path_abs')
KeyError: 'path_abs
```
sara.beckman: I tried running ddrimport file on 5.6_HQMA and it was successful

geoff.froh: Couple of quick summary points:
- error only applies to the manual new file upload from the webui; command line and the new batch webui importer both work
- from the stack trace, it looks like ddr-cmdln is throwing something because the absolute file path attribute is missing
- the affected vm build hasn’t yet been rolled out to all of the other archivists so it’s not currently a production bottleneck ( :wink: )

**Comment by gjost** [comment]
Fixed in `ddrcmdln` commit `bdd5590` and `ddrlocal` commit `48a15c0` and included in package `ddrlocal-master 5.6.1`
